-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Elokuva CASCADE;
DROP TABLE IF EXISTS Ohjaaja CASCADE;
DROP TABLE IF EXISTS Näyttelijä CASCADE;
DROP TABLE IF EXISTS Arvostelu CASCADE;
DROP TABLE IF EXISTS Tyylilaji CASCADE;